### ISSUE TITLE
Write to a binding 

### ISSUE THREAD

**Issue by K0IN** [rukodb/ruko#1]
Is there a way to write a value to an object retrieved by a binding operation 

example: 
`some_binding = self.db.create_mapping('my_cool_binding', 'some.*.object.*.with.*.many_childs.*')
`
now we assume the struct we searching looks like this
{
"id": str,
"data": int
} 

is there a way to write to this when doing an operation like:
`some_binding.by('id')["myid"]`

what I tried:
`some_binding.by('id')["myid"]["data"] = 1`

thing is it seems to work fine but the database never writes it to the disk, server configuration was: 
ENTRYPOINT [ "ruko-server" ]
CMD [ "0.0.0.0:44544", "--as-json", "--log-level", "debug" ]

**Comment by MatthewScholefield** [comment]
@K0IN Happy to see you stumbled upon this repo :). I've just pushed a fix in `ruko-server` that should fix this. Let me know if it works after recompiling.

**Comment by K0IN** [comment]
Yes now it works fine thanks a lot!
